### ISSUE TITLE
Can't import matplotlib on linux: module '_tkinter' has no attribute '__file__'

### ISSUE THREAD

**Issue by konstin** [astral-sh/python-build-standalone#129]
Basic matplotlib usage such as `import matplotlib.pyplot as plt; plt.plot(list(range(10)), list(range(10)))` crashes with `module '_tkinter' has no attribute '__file__'`. 

On system python, _tkinter is a shared library (`/usr/lib/python3.8/lib-dynload/_tkinter.cpython-38-x86_64-linux-gnu.so`), while in these python builds it's a builtin module which does not have `__file__`. matplotlib expects tkinter to be an .so it can load: 
https://github.com/matplotlib/matplotlib/blob/f25c2d025fa8f70d6688e7acf4b85e4eb7590299/src/_tkagg.cpp#L310-L322

To reproduce:

```bash
wget https://github.com/indygreg/python-build-standalone/releases/download/20220502/cpython-3.10.4+20220502-x86_64_v3-unknown-linux-gnu-pgo+lto-full.tar.zst
tar xf cpython-3.10.4+20220502-x86_64_v3-unknown-linux-gnu-pgo+lto-full.tar.zst
python/install/bin/python3 -m venv venv
venv/bin/pip install matplotlib
venv/bin/python -c "import matplotlib.pyplot as plt; plt.plot(list(range(10)), list(range(10)))"
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/konsti/monotrail/pbsi/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 2769, in plot
    return gca().plot(
  File "/home/konsti/monotrail/pbsi/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 2274, in gca
    return gcf().gca(**kwargs)
  File "/home/konsti/monotrail/pbsi/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 867, in gcf
    return figure()
  File "/home/konsti/monotrail/pbsi/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 808, in figure
    manager = new_figure_manager(
  File "/home/konsti/monotrail/pbsi/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 326, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "/home/konsti/monotrail/pbsi/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 316, in _warn_if_gui_out_of_main_thread
    if (_get_required_interactive_framework(_get_backend_mod())
  File "/home/konsti/monotrail/pbsi/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 217, in _get_backend_mod
    switch_backend(dict.__getitem__(rcParams, "backend"))
  File "/home/konsti/monotrail/pbsi/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 268, in switch_backend
    switch_backend(candidate)
  File "/home/konsti/monotrail/pbsi/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 288, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "/home/konsti/monotrail/pbsi/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 289, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "/home/konsti/monotrail/pbsi/python/install/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/konsti/monotrail/pbsi/venv/lib/python3.10/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/home/konsti/monotrail/pbsi/venv/lib/python3.10/site-packages/matplotlib/backends/_backend_tk.py", line 24, in <module>
    from . import _tkagg
AttributeError: module '_tkinter' has no attribute '__file__'. Did you mean: '__name__'?
```

Running `TCL_LIBRARY="$(pwd)/python/install/lib/tcl8.6" venv/bin/python -c "import matplotlib.pyplot as plt; plt.plot(list(range(10)), list(range(10)))"` instead as suggested by the docs makes no difference.

EDIT: I'm mainly using the standalone builds by libloading `libpython.so` and launching one of the very high level c api commands, so i'd be happy about any workaround that works with libloading or importlib hackery from rust.

**Comment by indygreg** [comment]
This is similar to https://github.com/indygreg/PyOxidizer/issues/69.

My general response to this is: `__file__` is documented as optional by Python: any code requiring `__file__` is bugged and should instead be using a mechanism described in https://pyoxidizer.readthedocs.io/en/pyoxidizer-0.20.0/oxidized_importer_resource_files.html.

But this case is more complex than simple resource file handling. It looks like matplotlib is opening the library in order for C code to get a handle on tk function symbols. 🤯

This is highly unorthodox, as it assumes C extensions are standalone libraries (an implementation detail of the Python distribution) and that said libraries export tk symbols (again, an implementation detail).

I'll likely need to converse with a matplotlib developer on how to best support this. I would like to have a compatibility story here, as matplotlib is a popular package and I'd like it to be supported.

**Comment by konstin** [comment]
fixed in matplotlib 🎉

**Comment by TsaiTung-Chen** [comment]
I'm building an GUI app using tkinter and matplotlib to plot some data. The tkagg backend is required to achieve this. I tried some dirty work to workaround this. Such as copy and paste a _tkinter SO file to the dynload folder and set the `__file__` attribute to that SO file path. However, I finally gave up to use this standalone distribution.

**Comment by driftregion** [comment]
I have encountered the same issue as @engnatha and @TsaiTung-Chen .  

https://github.com/bazelbuild/rules_python/issues/2540
https://github.com/matplotlib/matplotlib/issues/23074

**Comment by jkseppan** [comment]
@indygreg said:
> I'll likely need to converse with a matplotlib developer on how to best support this

I started to investigate a possible workaround on the matplotlib side by using Pillow's ImageTk, but I think I'm running into #533. Here's a minimal example:

```py
import tkinter as tk
from PIL import Image, ImageTk

img = Image.new('RGB', (200, 100), color = 'red')

root = tk.Tk()
root.title("PIL ImageTk Test")

photo = ImageTk.PhotoImage(img)
label = tk.Label(root, image=photo)
label.pack()

root.mainloop()
```

This opens a window with a red image on `/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13` but fails on `$HOME/.local/share/uv/python/cpython-3.13.5-macos-aarch64-none/bin/python3.13` with

```
Traceback (most recent call last):
  File "/Users/jks/src/matplotlib/.venv-uv/lib/python3.13/site-packages/PIL/ImageTk.py", line 59, in _pyimagingtkcall
    tk.call(command, photo, repr(ptr))
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: invalid command name "PyImagingPhoto"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jks/src/matplotlib/pil_tk_tester.py", line 9, in <module>
    photo = ImageTk.PhotoImage(img)
  File "/Users/jks/src/matplotlib/.venv-uv/lib/python3.13/site-packages/PIL/ImageTk.py", line 132, in __init__
    self.paste(image)
    ~~~~~~~~~~^^^^^^^
  File "/Users/jks/src/matplotlib/.venv-uv/lib/python3.13/site-packages/PIL/ImageTk.py", line 188, in paste
    _pyimagingtkcall("PyImagingPhoto", self.__photo, ptr)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jks/src/matplotlib/.venv-uv/lib/python3.13/site-packages/PIL/ImageTk.py", line 63, in _pyimagingtkcall
    from . import _imagingtk
TypeError: bad argument type for built-in operation
```

This is with pillow 11.2.1 installed from `pillow-11.2.1-cp313-cp313-macosx_11_0_arm64.whl`.

**Comment by geofft** [comment]
It looks like ImageTk is not going to work with current builds because it doesn't just need a working tkinter, it [looks for libtcl and libtk symbols directly](https://github.com/python-pillow/Pillow/blob/11.2.1/src/Tk/tkImaging.c), and we currently statically link those and do not re-export those for dynamic linking. And tkagg [does the same thing](https://github.com/matplotlib/matplotlib/blob/v3.10.3/src/_tkagg.cpp).

There are a few other use cases floating around for wanting to be able to use libtcl and libtk from C, not just wanting to use tkinter from Python. For instance, PyInstaller wants to use the Tcl/Tk libraries to display a splash screen before it's even running Python, and that currently doesn't work.

I'm going to reopen this since it sounds like the real goal is not just to import matplotlib but to have a working interactive backend, and it sounds like the easiest way to get there is to build libtcl, libtk, and `_tkinter` as shared libraries. That change will make things harder for the single-file static embedding use case, but it sounds like matplotlib already doesn't really work there, and ultimately this falls outside the scope of what the modern resources API (as indygreg/PyOxidizer#69 alludes to) can handle: the goal is not just to open and read _file_, but to locate and call a _symbol_, and the conventions around how to find symbols (and how to find the right one) are, at least at the moment, unavoidably tied up with dynamic linking and conventions around filenames.

(FWIW, the root cause of `TypeError: bad argument type for built-in operation` is that [`PIL._tkinter_finder.TKINTER_LIB` is set to `None`](https://github.com/python-pillow/Pillow/blob/11.2.1/src/PIL/_tkinter_finder.py#L18) if `_tkinter` is a shared library, but [`tkImaging.c` expects it to be either a string or not set](https://github.com/python-pillow/Pillow/blob/11.2.1/src/Tk/tkImaging.c#L449-L456) and ends up calling the C-API equivalent of `None.encode()`. This is adding to my belief that code paths around `_tkinter` being statically compiled into Python / `_tkinter.__file__` not existing are extremely untested and that it's safer not to trigger code paths that apparently no other Python distribution triggers.)

On a separate note, the [matplotlib docs](https://matplotlib.org/stable/users/explain/figure/backends.html) say there's a bunch of other backends like MacOSX or QtAgg or GTK4Agg—would people be better served using those instead of TkAgg?

**Comment by jkseppan** [comment]
> It looks like ImageTk is not going to work with current builds because it doesn't just need a working tkinter, it [looks for libtcl and libtk symbols directly](https://github.com/python-pillow/Pillow/blob/11.2.1/src/Tk/tkImaging.c)

Right, so my idea of punting the Tk interaction to Pillow runs into essentially the same problem there.

> On a separate note, the [matplotlib docs](https://matplotlib.org/stable/users/explain/figure/backends.html) say there's a bunch of other backends like MacOSX or QtAgg or GTK4Agg—would people be better served using those instead of TkAgg?

This is what I would recommend. Traditionally TkAgg was the easiest interactive backend to get working, since Python already shipped tkinter and all the others required extra libraries, so I think we still default to TkAgg (and people have scripts that call `matplotlib.use('tkagg')`). On a Mac, the MacOSX backend should work without extra dependencies.

**Comment by villares** [comment]
I'd like to chime in to respectfully stress that there are *a lot* of people using Tk/TkInter, it is not just the standard interactive matplotlib backend that you can work around using something else. This breaks many many libraries that depend on it.

I'm very grateful that @geofft is tackling this issue.

**Comment by cameron-simpson** [comment]
Chiming in myself. This bit me today with uv Pythons. On MacOS - this isn't just a Linux issue. I'm not doing anything interactive either, just generating a plot image.

All I need to trigger it is this:

    >>> import matplotlib.pyplot as plt; plt.subplots()

No attempt to render anything is needed.

No data scientist (I'm not one) is going to have the tools to work around this by picking other backends, or even to figure out that that is necessary or even possible.

I'm going to flail briefly at other backends, but more likely I'm just going to drop use of uv supplied Pythons.

I'm going to subscribe to this issue because really I'd love to see this to be fixed and be a nonissue for mpl users.

**Comment by geofft** [comment]
Just a quick status update, I'm working on this over in #676. (It's probably not very interesting/informative to look at while it's in progress, I know what's going on with the failing builds in CI, the harder problem is the successful builds that crash at runtime.) I'll update here when I have something for people to test, hopefully very soon. Appreciate all the test cases and issue pings!

And yes, the issue is for both Mac and Linux and the PR addresses them both. (I'm not currently looking at Windows but I think there's another issue reporting some separate tkinter issue there, I'll look at that once I get this change working.)

---

@cameron-simpson Since you're on a Mac, you should just need

```python
import matplotlib
matplotlib.use('macosx')
import matplotlib.pyplot as plt
...
```

What version of matplotlib are you on? `macosx` seems to be the default backend in the code for at least the last few years, and it's also the default for me when I try`uv run --with matplotlib python`. (If I specifically `matplotlib.use('tkagg')`, I can reproduce your failure.) Maybe you have a matplotlibrc file or something?

I really do think there are better backend choices than `tkagg`, but at least on Linux, those require non-default dependencies so we have to make sure `tkagg` works. On Mac you should be able to use the `macosx` backend and you shouldn't be getting `tkagg` unless you want it (but we should still make sure it works!).

**Comment by PathosV** [comment]
@geofft will the fix you're working towards be applicable to older python versions? I assume a reinstall would be needed but I'm curious if the fix would otherwise only be applicable to new python releases or not

**Comment by geofft** [comment]
The fix is applicable to all the Python versions we currently build, 3.9 onwards. Once the fix is released, uv users will need to upgrade uv itself and then `uv python install --reinstall`. I'll post the exact commands here once this is released in both python-build-standalone and uv.

**Comment by cameron-simpson** [comment]
> [@cameron-simpson](https://github.com/cameron-simpson) Since you're on a Mac, you should just need
> 
> import matplotlib
> matplotlib.use('macosx')
> import matplotlib.pyplot as plt
> ...

Yes, I've testing this via the environment variable by setting `$MPLBACKEND=MacOSX`. Thank you.

`matplotlib._get_version()` tells me `'3.10.3'`.

Definitely if I set `MPLBACKEND=` or unset it I get the tgagg based:
```
AttributeError: module '_tkinter' has no attribute '__file__'. Did you mean: '__name__'?
```
message from a uv-supplied python (3.13 was my test). Defaulting to MacOS would probably cover me, and it's what I've done for my environment on the Mac.

**Comment by geofft** [comment]
Hi all - I believe this should be resolved in the latest release.

For uv users, make sure you're using uv 0.8.8 and have updated your local Python versions:

```
uv self update
uv python upgrade --reinstall
```

For other python-build-standalone users, please make sure you're using today's release ([20250808](https://github.com/astral-sh/python-build-standalone/releases/20250808)).

Please try it out and let me know if there are remaining issues.

(By the way, if anyone sees _new_ bugs from this, please first open a new issue and at-mention me, and then use `uvx uv@0.8.6 python install --reinstall --no-bin 3.13.6` etc. to roll back to yesterday's 20250807 release. I don't expect this to break anything, but it is a pretty significant change in what's in the Python distributions and how things are linked, so it might have some unexpected side effects.)

**Comment by cameron-simpson** [comment]
> For uv users, make sure you're using uv 0.8.7 and have updated your local Python versions:
> 
> ```
> uv self update
> uv python install --reinstall --no-bin 3.13.6
> ```

Thank you, I've just tried this and it seems good. I'll do a proper run and actually plot something in a bit, but here's a test run (slightly edited to skip typos etc) showing my test example not raising the tkagg exception.

This goes:
- update `uv` in my default Python (a 3.12 from python.org)
- use that `uv` to reinstall 3.13.6 per your instructions
- make a venv from that new python
- install matplotlib in that venv
- run my test import and make a `subplots()`, which used to fail

```
[~]fleet2*2> py3 -m uv pip install -U uv
Using Python 3.12.9 environment at: var/venv/3.12-usr-local
Resolved 1 package in 6.47s
Prepared 1 package in 13.66s
Uninstalled 1 package in 6ms
Installed 1 package in 11ms
 - uv==0.8.4
 + uv==0.8.7
[~]fleet2*1> py3 -m uv python install --reinstall --no-bin 3.13.6
Installed Python 3.13.6 in 46.78s
 + cpython-3.13.6-macos-x86_64-none
[~]fleet2*> py3 -m uv python find cpython-3.13.6-macos-x86_64-none
/Users/cameron/.local/share/uv/python/cpython-3.13.6-macos-x86_64-none/bin/python3.13
[~]fleet2*> /Users/cameron/.local/share/uv/python/cpython-3.13.6-macos-x86_64-none/bin/python3.13
Python 3.13.6 (main, Aug  8 2025, 16:59:53) [Clang 20.1.4 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
[~]fleet2*> env - /Users/cameron/.local/share/uv/python/cpython-3.13.6-macos-x86_64-none/bin/python3.13 -m venv ~/var/venv/3.13-uv
[~]fleet2*> ~/var/venv/3.13-uv/bin/python3 -m pip install uv
Collecting uv
  Downloading uv-0.8.7-py3-none-macosx_10_12_x86_64.whl.metadata (11 kB)
Downloading uv-0.8.7-py3-none-macosx_10_12_x86_64.whl (18.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 2.1 MB/s  0:00:09
Installing collected packages: uv
Successfully installed uv-0.8.7
[~]fleet2*> ~/var/venv/3.13-uv/bin/python3 -m uv pip install matplotlib
Using Python 3.13.6 environment at: var/venv/3.13-uv
Resolved 11 packages in 4.92s
Installed 11 packages in 155ms
 + contourpy==1.3.3
 + cycler==0.12.1
 + fonttools==4.59.0
 + kiwisolver==1.4.8
 + matplotlib==3.10.5
 + numpy==2.3.2
 + packaging==25.0
 + pillow==11.3.0
 + pyparsing==3.2.3
 + python-dateutil==2.9.0.post0
 + six==1.17.0
[~]fleet2*> env - ~/var/venv/3.13-uv/bin/python3
Python 3.13.6 (main, Aug  8 2025, 16:59:53) [Clang 20.1.4 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
warning: can't use pyrepl: setupterm: could not find terminfo database
>>> import matplotlib.pyplot as plt; plt.subplots()
(<Figure size 640x480 with 1 Axes>, <Axes: >)
>>> ^D
```
The `env -` is to discard my `$MPLBACKEND` environment variable.

Thank you!

**Comment by josmithua** [comment]
> Hi all - I believe this should be resolved in the latest release.
> 
> For uv users, make sure you're using uv 0.8.7 and have updated your local Python versions:
> 
> ```
> uv self update
> uv python install --reinstall --no-bin 3.13.6
> ```

@geofft Possibly dumb question: Why the `--no-bin` option?

**Comment by zanieb** [comment]
Just so we don't install new `bin/` items if we hadn't previously. We changed that to the default behavior in the last version of uv though.

**Comment by geofft** [comment]
We just pushed a nicer command for it in uv 0.8.8, edited my comment above!
