### ISSUE TITLE
Issue with build cpython-3.8 on windows 10

### ISSUE THREAD

**Issue by TanyRay** [astral-sh/python-build-standalone#53]
Hi, I try to build cpython-3.8 on Windows 10 and got the issue:

```
Traceback (most recent call last):
  File "build.py", line 22, in <module>
    from pythonbuild.utils import (
  File "C:\Work\python-build-standalone\pythonbuild\utils.py", line 15, in <module>
    import zstandard
  File "C:\Work\python-build-standalone\build\venv\lib\site-packages\zstandard\__init__.py", line 36, in <module>
    import zstd
ModuleNotFoundError: No module named 'zstd'
```

Could someone suggest what to do?

**Comment by prescod** [comment]
When I had this same problem I fixed it by deleting everything and trying again. It was some kind of conflict between 32 bit and 64 bit binaries, I think.
